from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from config import LabConfig, load_config
from memory_store import estimate_tokens
from model_provider import build_chat_model


# ---------------------------------------------------------------------------
# Per-thread session state
# ---------------------------------------------------------------------------

@dataclass
class SessionState:
    """Holds all in-memory state for one thread_id."""

    messages: list[dict[str, str]] = field(default_factory=list)
    # Tokens generated by the assistant in this thread
    token_usage: int = 0
    # Cumulative prompt context processed across all turns
    # (grows linearly because baseline never compacts)
    prompt_tokens_processed: int = 0


# ---------------------------------------------------------------------------
# Baseline Agent
# ---------------------------------------------------------------------------

class BaselineAgent:
    """Agent A – within-session memory only.

    Design constraints
    ------------------
    - Keeps a simple message list per ``thread_id``.
    - No ``User.md``; no persistent storage of any kind.
    - Starting a new ``thread_id`` is a clean slate → agent forgets all facts.
    - Offline mode is deterministic and does not require an API key.
    - Live LangChain mode is optional; used only when all dependencies are
      available AND ``force_offline`` is False.
    """

    def __init__(
        self,
        config: LabConfig | None = None,
        force_offline: bool = False,
    ) -> None:
        self.config = config or load_config()
        self.force_offline = force_offline
        # Keyed by thread_id
        self.sessions: dict[str, SessionState] = {}
        # Attempt to build a live agent; falls back to None on any error
        self.langchain_agent = None
        if not force_offline:
            self._maybe_build_langchain_agent()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def reply(self, user_id: str, thread_id: str, message: str) -> dict[str, Any]:
        """Return the agent response and token accounting for one turn.

        Routes to the live LangChain path when available, otherwise falls
        back to the deterministic offline path.

        Returns
        -------
        dict with keys:
            response  : str   – assistant reply text
            thread_id : str
            tokens    : int   – tokens generated this turn
            prompt_tokens : int – prompt context size this turn
        """
        if self.langchain_agent is not None and not self.force_offline:
            return self._reply_live(user_id, thread_id, message)
        return self._reply_offline(thread_id, message)

    def token_usage(self, thread_id: str) -> int:
        """Return cumulative assistant tokens generated in *thread_id*."""
        return self.sessions.get(thread_id, SessionState()).token_usage

    def prompt_token_usage(self, thread_id: str) -> int:
        """Return cumulative prompt-context tokens processed in *thread_id*.

        For the baseline this grows linearly because the full message history
        is re-sent every turn without any compaction.
        """
        return self.sessions.get(thread_id, SessionState()).prompt_tokens_processed

    def compaction_count(self, thread_id: str) -> int:
        """Baseline has no compact memory – always returns 0."""
        return 0

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_or_create_session(self, thread_id: str) -> SessionState:
        if thread_id not in self.sessions:
            self.sessions[thread_id] = SessionState()
        return self.sessions[thread_id]

    def _reply_offline(self, thread_id: str, message: str) -> dict[str, Any]:
        """Deterministic offline reply.

        Behaviour
        ---------
        - Stores the user message in the session history.
        - Generates a short reply that can answer within-session recall
          questions by scanning the current thread's message history.
        - Never looks outside the current ``thread_id`` → forgets facts
          from other threads by design.
        - Updates ``token_usage`` and ``prompt_tokens_processed``.
        """
        session = self._get_or_create_session(thread_id)

        # Append user message
        session.messages.append({"role": "user", "content": message})

        # Estimate prompt cost = all messages so far (grows linearly)
        prompt_size = sum(
            estimate_tokens(m["content"]) for m in session.messages
        )
        session.prompt_tokens_processed += prompt_size

        # Build a response using only within-session history
        response = self._build_offline_response(session, message)

        # Append assistant reply
        session.messages.append({"role": "assistant", "content": response})

        # Track generated tokens
        gen_tokens = estimate_tokens(response)
        session.token_usage += gen_tokens

        return {
            "response": response,
            "thread_id": thread_id,
            "tokens": gen_tokens,
            "prompt_tokens": prompt_size,
        }

    def _build_offline_response(self, session: SessionState, question: str) -> str:
        """Generate a deterministic answer from within-session history.

        Strategy
        --------
        1. Collect all user messages in this thread as a mini knowledge base.
        2. Look for recall-question keywords (tên, nghề, nơi, đồ uống, …).
        3. Return the best matching fragment found in history, or a generic
           acknowledgement if nothing matches.

        Because the baseline has no persistent memory, answers to cross-session
        questions will simply say "mình chưa biết thông tin đó".
        """
        history_text = " ".join(
            m["content"] for m in session.messages if m["role"] == "user"
        )

        q_lower = question.lower()

        # --- Recall question dispatch ---
        fragments: list[str] = []

        if any(k in q_lower for k in ("tên", "name", "gọi")):
            import re
            m = re.search(
                r"(?:mình\s+tên\s+là|tên\s+(?:của\s+)?mình\s+là)\s+([^,\.\n!?]{2,30})",
                history_text,
                re.IGNORECASE,
            )
            if m:
                fragments.append(f"Tên: {m.group(1).strip()}")

        if any(k in q_lower for k in ("nghề", "làm", "công việc", "engineer", "manager")):
            import re
            jobs = re.findall(
                r"\b(MLOps\s+engineer|backend\s+engineer|frontend\s+engineer|"
                r"software\s+engineer|data\s+scientist|product\s+manager|"
                r"DevOps\s+engineer)\b",
                history_text,
                re.IGNORECASE,
            )
            if jobs:
                fragments.append(f"Nghề nghiệp: {jobs[-1]}")  # most recent mention

        if any(k in q_lower for k in ("ở đâu", "nơi ở", "địa chỉ", "thành phố", "sống")):
            import re
            locs = re.findall(
                r"\bở\s+(Đà\s*Nẵng|Huế|Hà\s*Nội|TP\.?\s*HCM|Sài\s*Gòn|Hội\s*An)\b",
                history_text,
                re.IGNORECASE,
            )
            if locs:
                fragments.append(f"Nơi ở: {locs[-1]}")

        if any(k in q_lower for k in ("đồ uống", "uống", "thức uống", "cà phê")):
            import re
            if re.search(r"cà\s*phê\s*sữa\s*đá", history_text, re.IGNORECASE):
                fragments.append("Đồ uống yêu thích: cà phê sữa đá")

        if any(k in q_lower for k in ("món ăn", "ăn", "thức ăn", "mì")):
            import re
            if re.search(r"mì\s*Quảng", history_text, re.IGNORECASE):
                fragments.append("Món ăn yêu thích: mì Quảng")

        if any(k in q_lower for k in ("style", "phong cách", "trả lời", "ngắn gọn", "bullet")):
            import re
            if re.search(r"ngắn\s*gọn", history_text, re.IGNORECASE):
                fragments.append("Style trả lời: ngắn gọn, rõ ý, có ví dụ thực tế")
            elif re.search(r"bullet", history_text, re.IGNORECASE):
                fragments.append("Style trả lời: thành bullet ngắn, có ví dụ thực tế")

        if any(k in q_lower for k in ("nuôi", "pet", "corgi", "chó", "mèo")):
            import re
            if re.search(r"corgi", history_text, re.IGNORECASE):
                fragments.append("Thú cưng: corgi")

        if any(k in q_lower for k in ("sở thích", "thích", "quan tâm")):
            import re
            if re.search(r"Python", history_text, re.IGNORECASE):
                fragments.append("Sở thích: Python, AI ứng dụng")

        if fragments:
            return "Dựa trên thông tin trong cuộc trò chuyện này:\n" + "\n".join(
                f"- {f}" for f in fragments
            )

        # Generic acknowledgement – no matching facts found in this thread
        last_user_words = question.strip()[:80]
        return (
            f"Mình đã ghi nhận: \"{last_user_words}\". "
            "Trong thread này mình chưa có thông tin để trả lời chi tiết hơn."
        )

    def _reply_live(self, user_id: str, thread_id: str, message: str) -> dict[str, Any]:
        """Live LangChain/LangGraph path (used only when agent is initialised)."""
        try:
            result = self.langchain_agent.invoke(
                {"messages": [{"role": "human", "content": message}]},
                config={"configurable": {"thread_id": thread_id}},
            )
            response = result["messages"][-1].content
            session = self._get_or_create_session(thread_id)
            session.messages.append({"role": "user", "content": message})
            session.messages.append({"role": "assistant", "content": response})
            gen_tokens = estimate_tokens(response)
            session.token_usage += gen_tokens
            prompt_size = sum(estimate_tokens(m["content"]) for m in session.messages)
            session.prompt_tokens_processed += prompt_size
            return {
                "response": response,
                "thread_id": thread_id,
                "tokens": gen_tokens,
                "prompt_tokens": prompt_size,
            }
        except Exception:
            # Fall back to offline on any live error
            return self._reply_offline(thread_id, message)

    def _maybe_build_langchain_agent(self) -> None:
        """Optionally wire LangChain ReAct agent with InMemorySaver.

        Silently skips if:
        - Required packages are not installed.
        - No API key is configured (provider key is None / empty).

        This keeps the offline benchmark path always available without
        needing LangChain or a paid API key.
        """
        try:
            from langgraph.checkpoint.memory import MemorySaver  # type: ignore
            from langgraph.prebuilt import create_react_agent  # type: ignore

            # Only proceed if we have a usable API key
            api_key = self.config.model.api_key
            if not api_key:
                return

            model = build_chat_model(self.config.model)
            memory = MemorySaver()
            self.langchain_agent = create_react_agent(model, tools=[], checkpointer=memory)
        except Exception:
            # Missing packages or bad config → stay offline
            self.langchain_agent = None
